import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "@/lib/antd.registry";
import './global.css'
import Provider from "./components/Provider";
import theme from '@/theme/themeConfig';
import { ConfigProvider } from "antd";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <StyledComponentsRegistry><Provider><ConfigProvider theme={theme}>{children}</ConfigProvider></Provider></StyledComponentsRegistry>
      </body>
    </html>
  );
}
